// <auto-generated />
using System;
using BlogAppNetCore.Data.Concrete.EntityFramework.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlogAppNetCore.Data.Migrations
{
    [DbContext(typeof(BlogAppContext))]
    [Migration("20210825092354_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlogAppNetCore.Entities.Concrete.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CommentCount")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SeoAuthor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SeoDescription")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SeoTags")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ViewsCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CommentCount = 1,
                            Content = "Geçtiğimiz haftalarda pandemi nedeniyle online düzenlenen Microsoft Build 2020 etkinliğinde birçok yenilik duyurusu yapıldı. Biz yazılım geliştiricilerin en ilgisini çekenlerden biri belki de C# 9 ile hangi yeniliklerin geleceğiydi. Build etkinliğinde duyurulan yeni C# dil özelliklerinden bazılarını bu makalede ele alıp inceleyeceğiz. Elbette gelecek olan yenilikler bu makalede anlatılanlarla sınırlı değil ve bazı yeniliklerin eklenip çıkarılabileceğini biliyoruz. Şunu hatırlatmakta fayda var; bu yazı Haziran 2020’de yazıldı ve henüz resmi bir C# 9 sürümü çıkmadı. Yazıda sadece Build etkinliğinde duyurulan ve yakın gelecekte karşımıza çıkması kuvvetle muhtemel C# 9 dil özelliklerinden bazılarına göz atacağız.Yeni gelecek özellikleri şu başlıklar altında inceleyelim:Target-type newBildiğiniz üzere sınıflar referans tiplerdir.Bir sınıfın örneğini almak için new operatörü kullanırız.C# 9‘dan önce bir sınıfın örneğini almak için aşağıdaki tanımlamayı yapmamız gerekiyordu. List customerNames = new List(); C# 9 ile beraber artık new operatörünü kullandıktan sonra bir tip belirtmemize gerek kalmıyor. Aşağıdaki tanımlama ve yukarıdaki tanımlama aslında aynı şeyi ifade etmekte. var keyword’ünün eşittir operatörünün sağ tarafına geçmiş haline benzetebiliriz sanırım bu kullanımı.List<string> customerNames = new();",
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2021, 8, 25, 12, 23, 53, 314, DateTimeKind.Local).AddTicks(8536),
                            Date = new DateTime(2021, 8, 25, 12, 23, 53, 314, DateTimeKind.Local).AddTicks(6266),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2021, 8, 25, 12, 23, 53, 314, DateTimeKind.Local).AddTicks(9699),
                            Note = "C# 9.0 Yenilikleri",
                            SeoAuthor = "Nadir Korkut",
                            SeoDescription = "C# 9.0 Yenilikleri",
                            SeoTags = "C#, C# 9",
                            Thumbnail = "Default.jpg",
                            Title = "C# 9.0 Yenilikleri",
                            UserId = 1,
                            ViewsCount = 100
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CommentCount = 1,
                            Content = "C++ dilinde kod geliştiren yazılımcılar, dilin 1998 yılında standartlaşmasının ardından, 2011 yılında C++11 standardı çıkana kadar uzunca bir süre kullandıkları dilde bir değişim olmadan yazılımlarını geliştirmeye devam etmişlerdi. Bu zaman zarfında gelişen ve değişen dünyadaki problemlere çözüm bulmak, C++ dilinde gittikçe zorlaşmış, üçüncü parti kütüphane desteği olmadan güncel problemlere çözüm sunamayan eski kalmış bir dil haline gelmişti. C++ geliştiricileri, Boost gibi kütüphaneler olmadan diğer yazılım dillerinin sağladığı özellikler ile yarışamaz bir durumdaydılar.Uzun bir aranın ardından yayınlanan C++11 standardı,mevcut dile birçok değişiklik getirmiş; C++ dilini adeta yeni bir dil haline getirmişti.Lambda expressions, auto, constexpr, future gibi yeni gelen özellikler ile bugün Modern C++olarak adlandırılan yeni bir dönem başlamış ve C++, diğer yazılım dilleri olan yarışında kendine tekrar üst sıralarda yer bulabilmişti.C++11 ile başlayan ve her 3 yılda bir güncellenen standart, geleneğini C++20 güncellemesi ile devam ettiriyor. C++14 ve C++17 standartları, C++11 ile gelen özelliklerin güçlendirilmesi, daha çok derleyici zamanında kod çalıştırılması gibi yenilikler getirirken, dile çok fazla veya çok büyük yenilikler getirmemişlerdi.Ancak, C++20 standardı ile birlikte gelen 4 büyük yenilik ve birçok yeni iyileştirme sayesinde C++dili, diğer diller ile olan rekabetinde yeni bir sayfa daha açacağa benziyor.Büyük dörtlü olarak ifade edilen, Concepts, Ranges, Coroutines ve Modules özelliklerinin dile eklenmesiyle birlikte, C++ dünyasını, tıpkı C++11 güncellemesi gibi büyük değişiklikler bekliyor.",
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2021, 8, 25, 12, 23, 53, 315, DateTimeKind.Local).AddTicks(2515),
                            Date = new DateTime(2021, 8, 25, 12, 23, 53, 315, DateTimeKind.Local).AddTicks(2513),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2021, 8, 25, 12, 23, 53, 315, DateTimeKind.Local).AddTicks(2516),
                            Note = "C++ 20 İle Gelen Yenilikler",
                            SeoAuthor = "Nadir Korkut",
                            SeoDescription = "C++ 20 İle Gelen Yenilikler",
                            SeoTags = "C++, C++ 20",
                            Thumbnail = "Default.jpg",
                            Title = "C++ 20 İle Gelen Yenilikler",
                            UserId = 1,
                            ViewsCount = 158
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CommentCount = 1,
                            Content = "Ne haber millet! JavaScript, harika bir programlama dili gelişiyor. ECMAScript 2020 (yaygın olarak ES2020 olarak bilinir) özelliklerinin artık TC39 komitesi tarafından tamamlandığına dair iyi haberi duymaktan mutluluk duyuyoruz.Yeni JavaScript'teki bazı ilginç özellikleri görelim.BigInt BigInt olan yerleşik bir daha büyük bir bütün sayıları temsil etmek için bir yol sağlar nesne POW(2, 53) - 1, JavaScript güvenilir bir şekilde temsil en büyük sayı olan Numarası ilkel ve ile temsil edilen Number.MAX_SAFE_INTEGER sabit.A BigInt,nbir tamsayı değişmezinin sonuna eklenerek veya işlevi çağırarak oluşturulur BigInt(). Bununla birlikte, BigInt kullanarak çok büyük sayıları temsil edebiliriz, BigInt türü normal sayılarla kullanıldığında bazı sınırlamalar vardır. Yerleşik Mathnesnedeki yöntemlerle kullanılamaz ve Numberişlemlerde örnekleri ile karıştırılamaz . Aynı tip ile kullanılmaları gerekir.BigInt,IEEE754 standartlarıyla geriye dönük olarak uyumlu değildir çünkü bu sayı sistemi çok büyük sayıları destekleyemez.İsteğe Bağlı ZincirlemeBu,JavaScript kodunuzun daha net görünmesini sağlayan heyecan verici özelliklerden biridir.İsteğe bağlı zincirleme?., bir ara özellik mevcut olmasa bile,yuvalanmış nesne özelliklerine erişmenin hatasız bir yoludur.Kulağa ilginç geliyor mu ? Bu özellik,derinlemesine iç içe geçmiş nesnenin her seviyesinde özellik varlığını kontrol etmek için çok sayıda kod satırı yazmayı kaydetmelidir.Bir nesnenin bir özelliğine ulaşmak istediğinizde, genellikle &&nesne boş veya tanımsız olduğunda hata almaktan kaçınmak için operatörü kullanabilirsiniz .Bu yeni JavaScript özelliği ile,bu sözdizimi yukarıdakinden daha iyi ve daha net hale gelir.Ağacın her seviyesi için operatör?.eklemek yerine kullanabilirsiniz &&.İsteğe bağlı zincirleme?.değerlendirme ve döner durur undefinedparçası önce,eğer?.bir undefinedya da null.",
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2021, 8, 25, 12, 23, 53, 315, DateTimeKind.Local).AddTicks(2523),
                            Date = new DateTime(2021, 8, 25, 12, 23, 53, 315, DateTimeKind.Local).AddTicks(2521),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2021, 8, 25, 12, 23, 53, 315, DateTimeKind.Local).AddTicks(2524),
                            Note = "JavaScript ES2020 Yenilikleri",
                            SeoAuthor = "Nadir Korkut",
                            SeoDescription = "JavaScript ES2020 Yenilikleri",
                            SeoTags = "JavaScript, JavaScript ES2020",
                            Thumbnail = "Default.jpg",
                            Title = "JavaScript ES2020 Yenilikleri",
                            UserId = 1,
                            ViewsCount = 14
                        });
                });

            modelBuilder.Entity("BlogAppNetCore.Entities.Concrete.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2021, 8, 25, 12, 23, 53, 318, DateTimeKind.Local).AddTicks(7970),
                            Description = "C# Programlama Dili İle İlgili En Güncel Bilgiler",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2021, 8, 25, 12, 23, 53, 318, DateTimeKind.Local).AddTicks(7983),
                            Name = "C#",
                            Note = "C# Blog Kategorisi"
                        },
                        new
                        {
                            Id = 2,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2021, 8, 25, 12, 23, 53, 318, DateTimeKind.Local).AddTicks(7998),
                            Description = "C++ Programlama Dili İle İlgili En Güncel Bilgiler",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2021, 8, 25, 12, 23, 53, 318, DateTimeKind.Local).AddTicks(8000),
                            Name = "C++",
                            Note = "C++ Blog Kategorisi"
                        },
                        new
                        {
                            Id = 3,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2021, 8, 25, 12, 23, 53, 318, DateTimeKind.Local).AddTicks(8004),
                            Description = "JavaScript Programlama Dili İle İlgili En Güncel Bilgiler",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2021, 8, 25, 12, 23, 53, 318, DateTimeKind.Local).AddTicks(8006),
                            Name = "JavaScript",
                            Note = "CJavaScript Blog Kategorisi"
                        });
                });

            modelBuilder.Entity("BlogAppNetCore.Entities.Concrete.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArticleId = 1,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2021, 8, 25, 12, 23, 53, 321, DateTimeKind.Local).AddTicks(1671),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2021, 8, 25, 12, 23, 53, 321, DateTimeKind.Local).AddTicks(1684),
                            Note = "C# Makale Yorumu",
                            Text = "Lorem Ipsum pasajlarının birçok çeşitlemesi vardır. Ancak bunların büyük bir çoğunluğu mizah katılarak veya rastgele sözcükler eklenerek değiştirilmişlerdir. Eğer bir Lorem Ipsum pasajı kullanacaksanız, metin aralarına utandırıcı sözcükler gizlenmediğinden emin olmanız gerekir. İnternet'teki tüm Lorem Ipsum üreteçleri önceden belirlenmiş metin bloklarını yineler. Bu da, bu üreteci İnternet üzerindeki gerçek Lorem Ipsum üreteci yapar. Bu üreteç, 200'den fazla Latince sözcük ve onlara ait cümle yapılarını içeren bir sözlük kullanır. Bu nedenle, üretilen Lorem Ipsum metinleri yinelemelerden, mizahtan ve karakteristik olmayan sözcüklerden uzaktır."
                        },
                        new
                        {
                            Id = 2,
                            ArticleId = 2,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2021, 8, 25, 12, 23, 53, 321, DateTimeKind.Local).AddTicks(1698),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2021, 8, 25, 12, 23, 53, 321, DateTimeKind.Local).AddTicks(1700),
                            Note = "C++ Makale Yorumu",
                            Text = "Lorem Ipsum pasajlarının birçok çeşitlemesi vardır. Ancak bunların büyük bir çoğunluğu mizah katılarak veya rastgele sözcükler eklenerek değiştirilmişlerdir. Eğer bir Lorem Ipsum pasajı kullanacaksanız, metin aralarına utandırıcı sözcükler gizlenmediğinden emin olmanız gerekir. İnternet'teki tüm Lorem Ipsum üreteçleri önceden belirlenmiş metin bloklarını yineler. Bu da, bu üreteci İnternet üzerindeki gerçek Lorem Ipsum üreteci yapar. Bu üreteç, 200'den fazla Latince sözcük ve onlara ait cümle yapılarını içeren bir sözlük kullanır. Bu nedenle, üretilen Lorem Ipsum metinleri yinelemelerden, mizahtan ve karakteristik olmayan sözcüklerden uzaktır."
                        },
                        new
                        {
                            Id = 3,
                            ArticleId = 3,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2021, 8, 25, 12, 23, 53, 321, DateTimeKind.Local).AddTicks(1704),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2021, 8, 25, 12, 23, 53, 321, DateTimeKind.Local).AddTicks(1705),
                            Note = "JavaScript Makale Yorumu",
                            Text = "Lorem Ipsum pasajlarının birçok çeşitlemesi vardır. Ancak bunların büyük bir çoğunluğu mizah katılarak veya rastgele sözcükler eklenerek değiştirilmişlerdir. Eğer bir Lorem Ipsum pasajı kullanacaksanız, metin aralarına utandırıcı sözcükler gizlenmediğinden emin olmanız gerekir. İnternet'teki tüm Lorem Ipsum üreteçleri önceden belirlenmiş metin bloklarını yineler. Bu da, bu üreteci İnternet üzerindeki gerçek Lorem Ipsum üreteci yapar. Bu üreteç, 200'den fazla Latince sözcük ve onlara ait cümle yapılarını içeren bir sözlük kullanır. Bu nedenle, üretilen Lorem Ipsum metinleri yinelemelerden, mizahtan ve karakteristik olmayan sözcüklerden uzaktır."
                        });
                });

            modelBuilder.Entity("BlogAppNetCore.Entities.Concrete.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2021, 8, 25, 12, 23, 53, 323, DateTimeKind.Local).AddTicks(1109),
                            Description = "Admin Rolü Tüm Haklara Sahiptir.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2021, 8, 25, 12, 23, 53, 323, DateTimeKind.Local).AddTicks(1124),
                            Name = "Admin",
                            Note = "Admin Rolüdür."
                        });
                });

            modelBuilder.Entity("BlogAppNetCore.Entities.Concrete.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("VARBINARY(500)");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2021, 8, 25, 12, 23, 53, 338, DateTimeKind.Local).AddTicks(2407),
                            Description = "İlk ADmin Kullanıcı",
                            Email = "nadirkorkutt@gmail.com",
                            FirstName = "Nadir",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Korkut",
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2021, 8, 25, 12, 23, 53, 338, DateTimeKind.Local).AddTicks(2421),
                            Note = "Admin Kullanıcısı",
                            PasswordHash = new byte[] { 98, 100, 48, 98, 49, 49, 50, 99, 53, 100, 53, 52, 54, 98, 99, 49, 48, 50, 56, 51, 102, 56, 97, 98, 100, 57, 48, 55, 56, 101, 101, 49 },
                            Picture = "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSX4wVGjMQ37PaO4PdUVEAliSLi8-c2gJ1zvQ&usqp=CAU",
                            RoleId = 1,
                            UserName = "nadirkorkut"
                        });
                });

            modelBuilder.Entity("BlogAppNetCore.Entities.Concrete.Article", b =>
                {
                    b.HasOne("BlogAppNetCore.Entities.Concrete.Category", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogAppNetCore.Entities.Concrete.User", "User")
                        .WithMany("Articles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BlogAppNetCore.Entities.Concrete.Comment", b =>
                {
                    b.HasOne("BlogAppNetCore.Entities.Concrete.Article", "Article")
                        .WithMany("Comments")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("BlogAppNetCore.Entities.Concrete.User", b =>
                {
                    b.HasOne("BlogAppNetCore.Entities.Concrete.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BlogAppNetCore.Entities.Concrete.Article", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("BlogAppNetCore.Entities.Concrete.Category", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("BlogAppNetCore.Entities.Concrete.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BlogAppNetCore.Entities.Concrete.User", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
